# Generated by Django 5.1.1 on 2024-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthive_app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
