# Generated by Django 5.1.1 on 2024-10-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthive_app', '0004_remove_donor_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval')], default='Pending Approval', max_length=20),
        ),
    ]
